DROP TABLE IF EXISTS CITTA;
DROP TABLE IF EXISTS REGIONE;
DROP TABLE IF EXISTS TIPOLOGIA_ESERCIZIO;
DROP TABLE IF EXISTS ESERCIZIO;
DROP TABLE IF EXISTS RELAZIONE_ESERCIZIO_TIPOLOGIA;

CREATE TABLE CITTA
(
	id		INTEGER PRIMARY KEY,
	nome	VARCHAR[50]
);

CREATE TABLE REGIONE
(
	id		INTEGER PRIMARY KEY,
	nome	VARCHAR[50]
);

CREATE TABLE TIPOLOGIA_ESERCIZIO
(
	id 			INTEGER PRIMARY KEY,
	descrizione	VARCHAR[50]
);

CREATE TABLE ESERCIZIO
(
	id			INTEGER PRIMARY KEY,
	nome		VARCHAR[50],
	indirizzo	VARCHAR[100],
	citta		INTEGER REFERENCES CITTA(id),
	regione		INTEGER REFERENCES REGIONE(id),
	telefono	VARCHAR[50],
	referente	VARCHAR[50],
	url			VARCHAR[50],
	UNIQUE (nome, indirizzo, citta)
);

CREATE TABLE RELAZIONE_ESERCIZIO_TIPOLOGIA
(
	esercizio	INTEGER REFERENCES ESERCIZIO(id),
	tipologia	INTEGER REFERENCES TIPOLOGIA_ESERCIZIO(id),
	PRIMARY KEY (esercizio, tipologia)
);